FROM openjdk:17-jdk-slim

WORKDIR /backend/gateway

COPY mvnw .
COPY .mvn .mvn
COPY pom.xml .
COPY src ./src

RUN chmod +x ./mvnw

EXPOSE 8080

ENV SPRING_DEVTOOLS_RESTART_ENABLED=true

CMD ["./mvnw", "spring-boot:run"]