FROM maven:3.9.5-eclipse-temurin-17

WORKDIR /backend/gateway

COPY mvnw .
COPY .mvn .mvn
COPY pom.xml .

COPY src ./src

# Poner dependencias en caché para evitar que se descarguen cada vez
RUN mvn dependency:go-offline

EXPOSE 8080

ENV SPRING_DEVTOOLS_RESTART_ENABLED=true

CMD ["mvn", "spring-boot:run"]